baseURL = 'https://achanda.dev/'
languageCode = 'en-us'
title = 'Abhishek Chanda'
theme = 'typo'

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'abap'
    tabWidth = 4

[params]
# Appearance
theme = 'light'

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = 'Hello!'
homeIntroContent = """
Hi! I am Abhishek (he/him). My interests are in Distributed systems and Infrastructure engineering.
I currently work as a staff engineer at Cloudflare, working on providing Postgres as a platform for internal teams.
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100
# Display summaries under post list entries
listSummaries = false
# List entries date format
listDateFormat = '2 Jan 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/abhichanda/"

[[params.social]]
name = "github"
url = "https://github.com/achanda"

[[params.social]]
name = "twitter"
url = "https://twitter.com/rony358"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

