baseURL = 'https://achanda.dev/'
languageCode = 'en-us'
title = 'Abhishek Chanda'
theme = 'typo'

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ['html', 'rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'abap'
    tabWidth = 4

[params]
# Appearance
theme = 'light'

# Intro on main page, content in markdown, if you omit title or content the other can be displayed
homeIntroTitle = 'Hello!'
homeIntroContent = """
I am Abhishek (he/him). I have wore many hats in the past, I have been a published author, a researcher, a software engineer, an SRE, 
a tech lead, a people manager. My current role is a staff engineer at Cloudflare where I am a part of the Postgres team. 
We provide Postgres as a managed service for Cloudflare. On any average day, we support up to 20% of the whole Internet’s traffic.

Other than work, I love to travel (been to 26 countries so far, lived in 3 countries) and hanging out with my family.
"""

# Collection to display on home page: 
# in this case we would display content/posts pages
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Pagination size across all website, this is the same for homepage and single list page
paginationSize = 100
# Display summaries under post list entries
listSummaries = false
# List entries date format
listDateFormat = '2 Jan 2006'

# Social icons
[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/abhichanda/"

[[params.social]]
name = "github"
url = "https://github.com/achanda"

[[params.social]]
name = "twitter"
url = "https://twitter.com/rony358"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"
breadcrumbs = true
